server:
  port: 8085

spring:
  application:
    name: customer
  
  datasource:
    url: jdbc:postgresql://localhost:5432/servicesdb # Update with your actual database URL
    username: user                                  # Your database username
    password: user                                  # Your database password
    driver-class-name: org.postgresql.Driver       # For PostgreSQL; adjust if using another DB

  jpa:
    hibernate:
      ddl-auto: update                              # Adjust as needed (e.g., create, validate)
    show-sql: true                                  # Show SQL queries in the logs
